### ISSUE TITLE
Change users functionalty and behavior

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#178]
Dear @honza801 and @catborise 
We already spoke about the users functionality and how it will be great users to be able to create their own VMs, depending of their rights - staff user or not for example, and not only wait for the admin to create and share VM to them.
Also users must see only their VMs and what the admin shared them + they must not be able to see and edit/manage computes, networks,storages, etc.
It will be great if a registration module can be created and where users can register. The newly registered users must go by default is some "guest user" permission mode, which should be something like view-only by my opinion, and the admin can change them to regular or staff users etc.
Can you spend some time and help to achieve this functionality? They way it is working now is more than stupid I think!
I use this platform in my small company and such changes will be very helpful for me and I believe for many other!
What will you say?

**Comment by honza801** [comment]
hi,

> We already spoke about the users functionality and how it will be great users to be able to create their own VMs, depending of their rights - staff user or not for example, and not only wait for the admin to create and share VM to them.
> Also users must see only their VMs and what the admin shared them + they must not be able to see and edit/manage computes, networks,storages, etc.

both is already possible.

> "registration module"

this should not be part of this project. every organisation has its own mechanisms to create new accounts for any services.

> They way it is working now...

i like the way it works now. actually i have configured SSO and automatic account creation.

> What will you say?

first two paragraphs are already implemented. if you need help with setup, describe your needs. registration module is not needed, since everybody is using different auth module. (i use apache kerberos auth). there are so many possibilities of authentication: apache (basic, digest, kerberos...), django (db, ldap...). maybe the simpliest way of doing new accounts for you: simple email form for new users. you can create new account in django admin module then.

cheers
fous

**Comment by Bandic007** [comment]
@honza801 
Is it possible to expose the green "+" button for user, which is staff user so that he can create a VM by himself?

**Comment by honza801** [comment]
hi,

can you use templates concept instead of creating new instances by the user?

honestly, i've never used the '+' button :) and don't know what is the magic behind it. we have several templates (installed debian/centos/freebsd/ubuntu...) shared for all users. users are cloning these templates. this makes new instances deployments faster (no need to go through installation process), users are happy :)

if any user needs to resize his vm, just give him staff role.

fous
