### ISSUE TITLE
Feature request: Ability to mark VMs to always run on different compute nodes 

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#229]
@catborise - recently I needed to have several VMs running always on different compute nodes to avoid down time if a compute node crash. Can you add such option to check (mark) in the VM options tab. Something like always run on compute node on which it was initially started, or always run on conpute node {compute node to select}.
And in addition to this the option to avoid running on the same compute node as {possibility to choose several VMs which to avoid}. This way when we have a cluster of VMs for example , we will avoid crash of the whole cluster.
In VMWare it is called host affinity rules or VM/Host rules
Is this achievable?

**Comment by Bandic007** [comment]
@catborise - I imagine something like this functionality from VMware ESXi:
![image](https://user-images.githubusercontent.com/39150122/54920550-288c5c80-4f0c-11e9-9551-da914c538c9e.png)

**Comment by catborise** [comment]
hi, 
this feature is related with cluster. There is not a cluster(pacemaker/corosync) mechanism on webvirtcloud. if there is a compute crash. There is not any mechanism to start them on the other nodes.
Cluster operations are risky and problematic operations.
you mention two things: 1. High Availability, 2. seperation rules

do you using pacemaker or alternatives?

you need this because of random start(CLONE_INSTANCE_AUTO_MIGRATE=True)?
