### ISSUE TITLE
Macvtap network support

### ISSUE THREAD

**Issue by purerosefallen** [retspen/webvirtcloud#291]
I can't create VMs with Macvtap network mode. I hope the future versions would support this. Thanks!

**Comment by faburem** [comment]
this would indeed be a great feature!

**Comment by catborise** [comment]
it was added. it should be working... 
have you tried?

**Comment by faburem** [comment]
indeed! I think the reason was that the host is new and there was no VM using macvtap before, after having manually changed the configuration of one it is now available for selection.. maybe the interface on the host was not even created before. Thanks for the hint! It is working fine now - I guess this issue can be closed then?
